language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq haskell-platform-doc
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - cabal update

  # Try installing some of the build-deps with apt-get for speed.
  - travis/cabal-apt-install $mode --force-reinstalls

install:
  - cabal configure -flib-Werror $mode
  - cabal build
  - cabal install --enable-documentation

script:
  - $script

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313structures\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"

env:
  - mode="--enable-tests" script="cabal test --show-details=always"
